apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: issuetracker-server
  namespace: issuetracker-dev
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: issuetracker-server
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
