FROM node:20-alpine AS build 
WORKDIR /app
COPY issuetracker.client/package*.json ./
RUN npm ci
COPY issuetracker.client/ ./
RUN npm run build -- --config vite.config.docker.js

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY issuetracker-infrastructure/Docker/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]