FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY IssueTracker.Server/ ./IssueTracker.Server/
RUN dotnet restore ./IssueTracker.Server/IssueTracker.Server.csproj
COPY IssueTracker.Server/ ./IssueTracker.Server/
RUN dotnet publish ./IssueTracker.Server/IssueTracker.Server.csproj \
    -c Release -o /app/publish
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/publish .

ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080

ENTRYPOINT ["dotnet", "IssueTracker.Server.dll"]