// <auto-generated />
using System;
using IssueTracker.Server.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IssueTracker.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260317153130_InitialCreate1")]
    partial class InitialCreate1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Investment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_Вложения");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Путь_Вложения");

                    b.Property<int>("TaskId")
                        .HasColumnType("integer")
                        .HasColumnName("ID_Задачи");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Тип_Вложения");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("Investment");
                });

            modelBuilder.Entity("List_Members", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("ID_Проекта");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("ID_Участника_проекта");

                    b.HasKey("ProjectId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("List_Members");
                });

            modelBuilder.Entity("Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_Проекта");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("integer")
                        .HasColumnName("ID_Администратора_проекта");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Наименование");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("Role", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Наименование_Роли");

                    b.HasKey("Name");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_Задачи");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Комментарий_к_задачи");

                    b.Property<string>("ComponentName")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Наименование_компонента");

                    b.Property<string>("DefectTypeName")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Наименование_Типа_дефекта");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Описание_задачи");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("Дата_последнего_изменения");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Наименование_модуля");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Приоритет_задачи");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("ID_Проекта");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime")
                        .HasColumnName("Дата_регистрации");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Наименование_Роли");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Статус_задачи");

                    b.Property<string>("TestCase")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Тест_кейс_дефекта");

                    b.HasKey("Id");

                    b.HasIndex("DefectTypeName");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RoleName");

                    b.ToTable("Task");
                });

            modelBuilder.Entity("Type_of_defect", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Наименование_Типа_дефекта");

                    b.HasKey("Name");

                    b.ToTable("Type_of_defect");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_Пользователя");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Логин");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Пароль");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Investment", b =>
                {
                    b.HasOne("Task", "Task")
                        .WithMany("Investments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("List_Members", b =>
                {
                    b.HasOne("Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project", b =>
                {
                    b.HasOne("User", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("Task", b =>
                {
                    b.HasOne("Type_of_defect", "DefectType")
                        .WithMany()
                        .HasForeignKey("DefectTypeName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DefectType");

                    b.Navigation("Project");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Task", b =>
                {
                    b.Navigation("Investments");
                });
#pragma warning restore 612, 618
        }
    }
}
