apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: issuetracker
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/PavelKrasko/IssueTracker.git  
    targetRevision: main                                        
    path: issuetracker-infrastructure/Helm/issuetracker         
  destination:
    server: https://kubernetes.default.svc  
    namespace: default                       
  syncPolicy:
    automated:
      selfHeal: true   
      prune: true      
    syncOptions:
      - CreateNamespace=true  
      