replicaCount: 1

image:
  registry: ghcr.io/pavelkrasko
  client:
    name: client
    tag: "1.0.1"
  pullPolicy: IfNotPresent

domain: "kraskotracker.duckdns.org"

backend:
  serviceName: issuetracker-server
  servicePort: 8080

service:
  port: 80