replicaCount: 1
domain: "kraskotracker.duckdns.org"

image:
  registry: ghcr.io/pavelkrasko
  client:
    name: client
    tag: 1.0.1
  server:
    name: server
    tag: 1.0.1

sqlserver:
  secretName: issuetracker-secrets
  storage: 10Gi
  saPassword: "MyPassword123!"
  database: IssueTrackerDB

tls:
  enabled: true
  clusterIssuer: letsencrypt-prod
  email: kraskopavel56@gmail.com