apiVersion: apps/v1
kind: Deployment
metadata:
  name: issuetracker-server
  labels:
    app: issuetracker-server
    app.kubernetes.io/name: issuetracker-server
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: issuetracker-server
  template:
    metadata:
      labels:
        app: issuetracker-server
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: server
          image: {{ .Values.image.registry }}/{{ .Values.image.server.name }}:{{ .Values.image.server.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ .Values.env.ASPNETCORE_ENVIRONMENT | quote }}
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.secretName }}
                  key: {{ .Values.db.connectionStringKey }}

