apiVersion: v1
kind: Service
metadata:
  name: issuetracker-client
  labels:
    app: issuetracker-client
    app.kubernetes.io/name: issuetracker-client
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app: issuetracker-client
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}