apiVersion: apps/v1
kind: Deployment
metadata:
  name: issuetracker-client
  labels:
    app: issuetracker-client
    app.kubernetes.io/name: issuetracker-client
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: issuetracker-client
  template:
    metadata:
      labels:
        app: issuetracker-client
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: client
          image: {{ .Values.image.registry }}/{{ .Values.image.client.name }}:{{ .Values.image.client.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80