apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: issuetracker-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.backend.serviceName }}
                port:
                  number: {{ .Values.backend.servicePort }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: issuetracker-client
                port:
                  number: {{ .Values.service.port }}
    