name: CI/CD pipline
on: [push]
jobs:
    build-client:
        runs-on: ubuntu-latest
        steps:
            - name: Install repository
              uses: actions/checkout@v4
            - name: Login to GHCR
              run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u pavelkrasko --password-stdin
            - name: Build Docker image
              run: |
                docker build \
                    -f Docker/Dockerfile.client
                    -t ghcr.io/pavelkrasko/issuetracker-client:latest \
                    .
            - name: Push Docker image
              run: docker push ghcr.io/pavelkrasko/issuetracker-client:latest