name: CI/CD Issuetracker

on:
  push:
    branches: ["main"]

jobs:
  build-client:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build \
            -f Docker/Dockerfile.client \
            -t ghcr.io/${{ github.repository_owner,, }}/issuetracker-client:latest \
            .

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/issuetracker-client:latest


  build-server:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v4

      - name: Build server
        run: echo "Building server..."
