name: CI/CD Issuetracker

on:
  push:
    branches: ["main"]

jobs:
  build-client:
    runs-on: ubuntu-latest
    env:
      GHCR_REGISTRY: ghcr.io
      GHCR_OWNER: pavelkrasko
      IMAGE_NAME: issuetracker-client
      IMAGE_TAG: latest

    steps:
      - name: Download repository
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.GHCR_REGISTRY }} -u ${{ env.GHCR_OWNER }} --password-stdin

      - name: Build Docker image
        run: |
          docker build \
            -f Docker/Dockerfile.client \
            -t ${{ env.GHCR_REGISTRY }}/${{ env.GHCR_OWNER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
            .

      - name: Push Docker image
        run: docker push ${{ env.GHCR_REGISTRY }}/${{ env.GHCR_OWNER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}