name: CI/CD pipeline
on: [push]
jobs:
    build-client:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Login to GHCR
              run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u pavelkrasko --password-stdin
            - name: Build Docker image
              env:
                DOCKER_BUILDKIT: 0
              run: |
                docker build \
                  -f infra/docker/Dockerfile.client \
                  -t ghcr.io/pavelkrasko/issuetracker-client:latest \
                  -t ghcr.io/pavelkrasko/issuetracker-client:${{ github.sha }} \
                  .
            - name: Push Docker image
              run: |
                docker push ghcr.io/pavelkrasko/issuetracker-client:latest
                docker push ghcr.io/pavelkrasko/issuetracker-client:${{ github.sha }}
    build-server:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Login to GHCR
              run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u pavelkrasko --password-stdin

            - name: Build Docker image
              env:
                DOCKER_BUILDKIT: 0
              run: |
                docker build \
                  -f infra/docker/Dockerfile.server \
                  -t ghcr.io/pavelkrasko/issuetracker-server:latest \
                  -t ghcr.io/pavelkrasko/issuetracker-server:${{ github.sha }} \
                  .
            - name: Push Docker image
              run: |
                docker push ghcr.io/pavelkrasko/issuetracker-server:latest
                docker push ghcr.io/pavelkrasko/issuetracker-server:${{ github.sha }}
