apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.sqlserver.secretName }}
type: Opaque
data:
  saPassword: {{ .Values.sqlserver.saPassword | b64enc }}
  connectionString: {{ printf "Server=mssql,1433;Database=%s;User Id=sa;Password=%s;TrustServerCertificate=True;" .Values.sqlserver.database .Values.sqlserver.saPassword | b64enc }}
