apiVersion: apps/v1
kind: Deployment
metadata:
  name: issuetracker-server
  labels:
    app: issuetracker-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: issuetracker-server
  template:
    metadata:
      labels:
        app: issuetracker-server
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: server
          image: {{ .Values.image.registry }}/{{ .Values.image.server.name }}:{{ .Values.image.server.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.sqlserver.secretName }}
                  key: connectionString
            - name: ASPNETCORE_ENVIRONMENT
              value: Production